[tool.qpro]
[[tool.qpro.server_targets]]
user = ""
host = ""
path = ""
port = "22"

[tool.qpro.config]
build = "rm -rf dist; python3 setup.py sdist"
entry_point = "setup.py"
executable = "twine upload dist/*"
input_file = ""
template_root = ""
